### ISSUE TITLE
Best weights

### ISSUE THREAD

**Issue by andrewcz** [cvxgrp/cptopt#1]
Hi  thank you for releasing the code.
How do you pull back the best weights after the optimization.

Kind regards and thanks,
Andrew

**Comment by phschiele** [comment]
Hi Andrew, 
thanks for opening the first issue :tada: 
All optimizers have a `.weights` property that you can query after the optimization.

**Comment by phschiele** [comment]
Added this to the example in the readme.
https://github.com/cvxgrp/cptopt
