### ISSUE TITLE
cvxpy requirement

### ISSUE THREAD

**Issue by ricnov** [cvxgrp/cptopt#2]
Hi,

In the setup.cfg and the readme files the cvxpy is required to be at least version 1.3, but as far as I know the latest version is 1.2.1, here's the reference https://pypi.org/project/cvxpy/#history . Is it correct? Thanks again

**Comment by phschiele** [comment]
That's right, this repo requires the `dotsort` atom, which will only be available in CVXPY 1.3, which will be released soon. Until then, you will need to install from source (see the README of this repo for the exact command to do that).
